version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: chessaroo-postgres-dev
    environment:
      POSTGRES_DB: chessaroo
      POSTGRES_USER: chessaroo_user
      POSTGRES_PASSWORD: chessaroo_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_dev_data:
